# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations:
        enabled: false
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    # Enable PHP error logging
    php_errors:
        log: true

    # Configure asset paths
    assets:
        base_path: '/startbootstrap-shop-homepage-gh-pages'

# Configuration specific to the test environment
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
